# Generated by Django 5.1.3 on 2025-02-07 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, default='college', max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=25, null=True)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('Date_of_birth', models.DateField(blank=True, null=True)),
                ('Image', models.FileField(upload_to='')),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Father_name', models.CharField(blank=True, max_length=20, null=True)),
                ('Mother_name', models.CharField(blank=True, max_length=20, null=True)),
                ('Gender', models.CharField(blank=True, max_length=10, null=True)),
                ('City', models.CharField(blank=True, max_length=20, null=True)),
                ('phonenumber', models.IntegerField(blank=True, null=True)),
                ('Addar_num', models.IntegerField(blank=True, null=True)),
                ('Qualification', models.CharField(blank=True, max_length=20, null=True)),
                ('Address', models.CharField(blank=True, max_length=20, null=True)),
                ('Vehiclenumber', models.CharField(blank=True, max_length=100, null=True)),
                ('Latitude', models.CharField(blank=True, max_length=100, null=True)),
                ('Longitude', models.CharField(blank=True, max_length=100, null=True)),
                ('University', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, default='active', max_length=10, null=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user_pages', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(blank=True, max_length=25, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='Assigntask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(blank=True, max_length=100, null=True)),
                ('task_description', models.CharField(blank=True, max_length=100, null=True)),
                ('task_status', models.CharField(blank=True, max_length=100, null=True)),
                ('task_deadline', models.DateField(blank=True, null=True)),
                ('userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignerid', to='myapp.usermodel')),
                ('volunteerid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volunteerid', to='myapp.usermodel')),
            ],
        ),
    ]
