# Generated by Django 5.1.3 on 2025-02-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logintable',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='Image',
            field=models.FileField(blank=True, null=True, upload_to='profileimages'),
        ),
    ]
