# Generated by Django 5.1.3 on 2025-02-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_logintable_type_alter_usermodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='assigntask',
            name='Latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='assigntask',
            name='Longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
