# Generated by Django 5.1.3 on 2025-02-08 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_assigntask_latitude_assigntask_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assigntask',
            old_name='Latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='assigntask',
            old_name='Longitude',
            new_name='longitude',
        ),
    ]
