# Generated by Django 5.1.6 on 2025-02-24 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_latitude_assigntask_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidenttable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_name', models.CharField(blank=True, max_length=100, null=True)),
                ('incident_description', models.CharField(blank=True, max_length=100, null=True)),
                ('incident_latitude', models.CharField(blank=True, max_length=100, null=True)),
                ('incident_longitude', models.CharField(blank=True, max_length=100, null=True)),
                ('reported_date', models.DateField(blank=True, null=True)),
                ('userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigner_id', to='myapp.usermodel')),
                ('volunteerid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volunteer_id', to='myapp.usermodel')),
            ],
        ),
    ]
