# Generated by Django 5.1.6 on 2025-02-24 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_incidenttable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emergencyalerttable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_name', models.CharField(blank=True, max_length=100, null=True)),
                ('alert_description', models.CharField(blank=True, max_length=100, null=True)),
                ('alert_latitude', models.CharField(blank=True, max_length=100, null=True)),
                ('alert_longitude', models.CharField(blank=True, max_length=100, null=True)),
                ('alert_reported_date', models.DateField(blank=True, null=True)),
                ('userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_assigner_id', to='myapp.usermodel')),
                ('volunteerid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_volunteer_id', to='myapp.usermodel')),
            ],
        ),
    ]
