# Generated by Django 5.1.6 on 2025-02-25 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_emergencyalerttable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorytable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=100, null=True)),
                ('category_description', models.CharField(blank=True, max_length=100, null=True)),
                ('category_status', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resourcetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_name', models.CharField(blank=True, max_length=100, null=True)),
                ('alert_description', models.CharField(blank=True, max_length=100, null=True)),
                ('alert_latitude', models.CharField(blank=True, max_length=100, null=True)),
                ('alert_longitude', models.CharField(blank=True, max_length=100, null=True)),
                ('alert_reported_date', models.DateField(blank=True, null=True)),
                ('userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_assigner_id', to='myapp.usermodel')),
                ('volunteerid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_volunteer_id', to='myapp.usermodel')),
            ],
        ),
    ]
