# Generated by Django 5.1.6 on 2025-02-25 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_categorytable_resourcetable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourcetable',
            old_name='alert_description',
            new_name='res_amount',
        ),
        migrations.RenameField(
            model_name='resourcetable',
            old_name='alert_latitude',
            new_name='res_description',
        ),
        migrations.RemoveField(
            model_name='resourcetable',
            name='alert_longitude',
        ),
        migrations.RemoveField(
            model_name='resourcetable',
            name='alert_reported_date',
        ),
        migrations.AddField(
            model_name='resourcetable',
            name='inc_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.incidenttable'),
        ),
        migrations.AddField(
            model_name='resourcetable',
            name='res_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.categorytable'),
        ),
    ]
