# Generated by Django 5.1.6 on 2025-02-25 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_alert_description_resourcetable_res_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedbacktable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_name', models.CharField(blank=True, max_length=100, null=True)),
                ('feedback_description', models.CharField(blank=True, max_length=100, null=True)),
                ('inc_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.incidenttable')),
                ('userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_assigner_id', to='myapp.usermodel')),
                ('volunteerid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_volunteer_id', to='myapp.usermodel')),
            ],
        ),
    ]
