# Generated by Django 5.1.6 on 2025-02-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_feedbacktable'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbacktable',
            name='feedback_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
