# Generated by Django 5.1.6 on 2025-02-25 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_feedbacktable_feedback_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requesttable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_name', models.CharField(blank=True, max_length=100, null=True)),
                ('request_description', models.CharField(blank=True, max_length=100, null=True)),
                ('request_status', models.CharField(blank=True, default='pending', max_length=100, null=True)),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.resourcetable')),
                ('userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_id', to='myapp.usermodel')),
            ],
        ),
    ]
