# Generated by Django 5.1.6 on 2025-02-26 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_requesttable_request_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcetable',
            name='res_quantity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
