# Generated by Django 5.1.6 on 2025-02-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_resourcetable_res_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttable',
            name='request_allocated_quantity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
