# Generated by Django 5.1.6 on 2025-02-28 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_requesttable_request_allocated_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidenttable',
            name='incident_reply',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_name', models.CharField(blank=True, max_length=100, null=True)),
                ('complaint_description', models.CharField(blank=True, max_length=100, null=True)),
                ('complaint_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('complaint_status', models.CharField(blank=True, default='pending', max_length=100, null=True)),
                ('userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.usermodel')),
            ],
        ),
    ]
