# Generated by Django 5.1.6 on 2025-03-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_incidenttable_incident_reply_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidenttable',
            name='incident_image',
            field=models.FileField(blank=True, null=True, upload_to='incidentimage'),
        ),
    ]
