# Generated by Django 5.1.6 on 2025-03-06 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_incidenttable_incident_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amounttable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_name', models.CharField(blank=True, max_length=100, null=True)),
                ('amount_description', models.CharField(blank=True, max_length=100, null=True)),
                ('amount_status', models.CharField(blank=True, max_length=100, null=True)),
                ('category_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.categorytable')),
            ],
        ),
    ]
